# Generated by Django 2.2.28 on 2022-11-17 15:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('send', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LayoutEmail',
            new_name='MailingEmail',
        ),
    ]
