# Generated by Django 2.2.28 on 2022-11-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0001_initial'),
        ('send', '0002_auto_20221117_1848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingemail',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Рассылка письма', 'verbose_name_plural': 'Рассылки писем'},
        ),
        migrations.AddField(
            model_name='mailingemail',
            name='subscriber',
            field=models.ManyToManyField(to='subscriber.Subscriber'),
        ),
        migrations.AlterField(
            model_name='mailingemail',
            name='text',
            field=models.TextField(verbose_name='Рассылка письма'),
        ),
    ]
