# Generated by Django 2.2.28 on 2022-11-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0003_auto_20221117_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingemail',
            name='topic',
            field=models.TextField(default=312412, verbose_name='Тема письма'),
            preserve_default=False,
        ),
    ]
